### ISSUE TITLE
Chapter 1: Introduction to React

### ISSUE THREAD

**Issue by JimmyLv** [the-road-to-learn-react/the-road-to-learn-react-chinese#1]
翻译时间：14 天（预估时间：2017年 12 月 2 日 - 2017 年 12 月 16日）
翻译作者：@kenpusney (Kimmy Leo)、@SBeator (Xingxin Zeng)

校对时间：x 天（预估时间：x 年 x 月 x 日 - x 年 x 月 x 日）
校对作者：

**Comment by kenpusney** [comment]
看来只剩下这个给我了？

**Comment by SBeator** [comment]
加我一个吧， @kenpusney 我们一起？

**Comment by kenpusney** [comment]
预估时间…哎呀妈，大面积文字啊。

两周？

**Comment by JimmyLv** [comment]
@SBeator @kenpusney 你们协调一下分一下 Task，然后估个时间吧~ 👍

**Comment by SBeator** [comment]
和 @kenpusney 协调好了，翻译时间预估14 天（2017年 12 月 2 日 - 2017 年 12 月 16日）

**Comment by kenpusney** [comment]
@JimmyLv #24 第一部分，ready to review

**Comment by JimmyLv** [comment]
为了保持这一章的风格一致，你们先互相 review 一波可以嘛？

@kenpusney @SBeator
