### ISSUE TITLE
进来讨论一下中文书名？《React 斩荆之路》怎么样？

### ISSUE THREAD

**Issue by JimmyLv** [the-road-to-learn-react/the-road-to-learn-react-chinese#10]
备选方案

- [ ] 《React 学习之路》
- [ ] 《React 斩荆之路》
- [ ] 《通往 React 之路》
- [ ] 《React 快速进阶指南》
- [ ] 《React 学习之道》
- [ ] ...

**Comment by kenpusney** [comment]
“通往React之路”
以前在某些书里见到过，不过有点太直接，而且也很奇怪。（

**Comment by JimmyLv** [comment]
哈哈，已加入备选。

最后出一个金数据在群里征集一下投票好了。

**Comment by azzgo** [comment]
<img width="1104" alt="screen shot 2017-12-01 at 22 49 01" src="https://user-images.githubusercontent.com/5636512/33487927-e7dc7eb8-d6e9-11e7-9396-d3ee685be1fa.png">
我是来搞笑的

**Comment by JimmyLv** [comment]
哈哈哈，这么说《学习 React 的道路》也是很接地气的。😂

**Comment by LeiZeng** [comment]
我觉得先不要考虑原名，意译吧，比如《React快速进阶指南》。。。

**Comment by LeiZeng** [comment]
想到一个新的，《React学习之道》
