### ISSUE TITLE
翻译总览：讨论流程、规范、技巧等等一切问题

### ISSUE THREAD

**Issue by JimmyLv** [the-road-to-learn-react/the-road-to-learn-react-chinese#11]
## 如何参与翻译？

1. 挑选章节：在相应 Issue 里面回复即可（稍后发送[权限 invitation](https://github.com/the-road-to-learn-react/the-road-to-learn-react-chinese/settings/collaboration)）
2. 协调时间/人员：跟你共同翻译的小伙伴协商 tasks 和相应的预估时间
3. fork 项目：clone 至本地，推荐 Markdown 编辑器 [Typora](https://www.typora.io/)
4. 翻译：新建 `*-cn.md` 文件，如 `chapter1-cn.md`
5. 提 Pull Request：同时艾特 `@` 做校对的小伙伴
6. Review：直接在 PR 内对应 commits 位置进行评论与讨论
7. 合并：翻译完成，`大吉大利，晚上吃鸡！`

## 翻译的流程和工具有哪些？

- 使用了类似 Trello 的管理工具 [ZenHub](https://www.zenhub.com/)，具备 Pipeline、Estimate、Assignees 等功能，可视化翻译进度。
- 安利一下好用的 Markdown 编辑器 [Typora](https://www.typora.io/)，功能完备且美观，当然也可以用 Sublime 或者 Intellij 呀，😂
- 可以适当借助 Google 翻译，回过头来看你可能会说，~~卧槽 Google Translate 真是牛逼！~~

## 翻译时有木有什么小技巧？（欢迎随时补充）

你可以分段将英文和译文放在一起，例如：

------

> The chapter gives you an introduction to React. You may ask yourself: Why should I learn React in the first place? 

本章介绍 React。你可能会问自己：为何应当优先学习 React？

------

1. 方便翻译时进行双语对照、2. 引用符号 `>` 方便翻译完成后一键移除英文（regex）

## 翻译时的常用词汇约定可以参看 issue #19 用词规范

**Comment by azzgo** [comment]
好的，学习下

**Comment by LeiZeng** [comment]
有一些细节，比如对读者的“你”，要不要用“您”；对本书的指代，要统一用“她它他“吗

**Comment by azzgo** [comment]
还有英文和中文间要统一加空格么，现在我是这么做的

**Comment by liujiefengfeng** [comment]
对读者的“你” “您”，我统一翻译成了 我们。

**Comment by zengyang2014** [comment]
对读者的“你” “您”，我用了你。。。要不要统一一下
