### ISSUE TITLE
用词规范

### ISSUE THREAD

**Issue by lazurey** [the-road-to-learn-react/the-road-to-learn-react-chinese#19]
大家来把一些常用词汇在这里记录一下应该翻译成什么吧，方便各自查找。

| 原文 | 中文 |
| -- | -- |
| command line | 命令行 |
| repository | *TBD* |
| hook | *TBD* |
| functional stateless components | 1. 函数式无状态组件 2. 无状态组件 |
| bug | 可以视上下文不翻译 |

**Comment by azzgo** [comment]
| 原文 | 中文 |
| -- | -- |
|the practical application | 练习项目 ？？|

TBD啥意义啊

**Comment by lazurey** [comment]
`the practical application` 是指“现实中的应用、实际的应用”的意思吧

TBD = to be decided

command line现在有两种翻译： 1 ）命令行； 2）终端；
repository：1）代码库；2）代码版本库

**Comment by JimmyLv** [comment]
终端 should be `terminal` ?

**Comment by liujiefengfeng** [comment]
| 原文 | 中文 |
| -- | -- |
| arrow function block body | 块体箭头函数 |
| mount | 挂载 |


command line 我翻译的是 命令行

**Comment by azzgo** [comment]
命令行吧

**Comment by JimmyLv** [comment]
作者经常安利他写的第二本（Taming the State in React），我们来统一一下翻译？

~~《驯服 React 中的状态》 via @JimmyLv~~
《驾驭 React 中的状态》 via @futantan 
……
