### ISSUE TITLE
Chapter 2: Basics in React

### ISSUE THREAD

**Issue by JimmyLv** [the-road-to-learn-react/the-road-to-learn-react-chinese#2]
翻译时间：x 天（预估时间：x 年 x 月 x 日 - x 年 x 月 x 日）
翻译作者：@ariesjia (Chenjia) 、@Yixi ( 一兮 )、@HelloRuiLi（李睿） 

校对时间：x 天（预估时间：x 年 x 月 x 日 - x 年 x 月 x 日）
校对作者：@trotyl (Trotyl Yu) 、@lazurey
校对 PR：#13

**Comment by ariesjia** [comment]
这个有点长 有没有小伙伴一起来

**Comment by Yixi** [comment]
来 我俩一起

**Comment by JimmyLv** [comment]
👍 赞赞赞！ 

来估个时间吧，Deadline Driven Development 哈哈哈~

**Comment by reeli** [comment]
可以加我一个吗？我也想翻译这章

**Comment by Yixi** [comment]
来一起吧，这篇挺长的

**Comment by reeli** [comment]
@Yixi @ariesjia 我们先来分一下任务吧，趁周末比较闲可以动手开始翻译啦~

**Comment by reeli** [comment]
![image](https://user-images.githubusercontent.com/8966348/33485672-37679bc8-d6e2-11e7-8bb8-369300c1060d.png)
一共有13章，我想翻译最后这五章。

**Comment by ariesjia** [comment]
1-4 @ariesjia    5-8 @Yixi    9-13 @HelloRuiLi

**Comment by JimmyLv** [comment]
👍 太棒！预估个时间有木有？

btw 嘉哥快去 accept 一下[权限](https://github.com/the-road-to-learn-react/the-road-to-learn-react-chinese/invitations)吧。

**Comment by JimmyLv** [comment]
@trotyl 既然泽江已经开始 review 了，我就把你放到上面的校对作者里面哦，快去接受一下权限然后我把这张卡拖到 `In Review` 那一列哈。 Cheers! 

https://github.com/the-road-to-learn-react/the-road-to-learn-react-chinese/invitations
