### ISSUE TITLE
Chapter 3: Getting Real with an API

### ISSUE THREAD

**Issue by JimmyLv** [the-road-to-learn-react/the-road-to-learn-react-chinese#3]
翻译时间：14天（预估时间：2017年 12 月 4 日 - 2017 年 12 月 18 日）
翻译作者：@zengyang2014（曾扬）

校对时间：x 天（预估时间：x 年 x 月 x 日 - x 年 x 月 x 日）
校对作者：@lazurey

**Comment by zengyang2014** [comment]
翻译时间：14天（预估时间：2017年 12 月 4 日 - 2017 年 12 月 18 日）
翻译作者：曾扬

校对时间：7天（预估时间：2017年 12 月  18日 - 2017 年 12 月 25 日）

**Comment by JimmyLv** [comment]
校对最好找别的小伙伴哦，anyway 到时候 PR 的时候直接 `@` 人过来看。

**Comment by zengyang2014** [comment]
👌
