### ISSUE TITLE
中文版的几个文字错误

### ISSUE THREAD

**Issue by zxhycxq** [the-road-to-learn-react/the-road-to-learn-react-chinese#39]
1、似乎多了一个“的”。大约有三处是这样。
![image](https://user-images.githubusercontent.com/11674203/35481155-210710a8-0459-11e8-96c7-b49303f2b2e3.png)
2、“再”似乎应该是“在”。
![image](https://user-images.githubusercontent.com/11674203/35481183-a45adff2-0459-11e8-9701-05d0a780b8f3.png)

**Comment by JimmyLv** [comment]
非常感谢你的反馈，已修改并发布新的版本。
