### ISSUE TITLE
Chapter 4: Code Organization and Testing

### ISSUE THREAD

**Issue by JimmyLv** [the-road-to-learn-react/the-road-to-learn-react-chinese#4]
翻译时间：7 天（预估时间：2017 年 12 月 02 日 - 2017 年 12 月 08 日）
翻译作者：@azzgo （一山）

校对时间：x 天（预估时间：x 年 x 月 x 日 - x 年 x 月 x 日）
校对作者：

**Comment by azzgo** [comment]
我要领这章，先估个一周时间吧，从12-02开始 到 12-08号吧
