### ISSUE TITLE
几个语义不顺的地方

### ISSUE THREAD

**Issue by xuexiaoao** [the-road-to-learn-react/the-road-to-learn-react-chinese#40]
#### 第一处
![image](https://user-images.githubusercontent.com/18185523/35516938-0cb10970-0548-11e8-983c-232f4d9f24c6.png)
#### 第二处
![image](https://user-images.githubusercontent.com/18185523/35517879-baf95f3a-054a-11e8-8c2f-8e993d4ba33c.png)

**Comment by JimmyLv** [comment]
多谢反馈，已修复并发布新版本。
