### ISSUE TITLE
几处错别字

### ISSUE THREAD

**Issue by Heroor** [the-road-to-learn-react/the-road-to-learn-react-chinese#42]
1. 使用真实的 API  [chapter3-cn.md](https://github.com/the-road-to-learn-react/the-road-to-learn-react-chinese/blob/master/manuscript/chapter3-cn.md)  
> 之后，因为状态的**更新，更新**生命周期开始运行。组件再次执行 render() 方法...

2. 代码组织和测试 [chapter4-cn.md](https://github.com/the-road-to-learn-react/the-road-to-learn-react-chinese/blob/master/manuscript/chapter4-cn.md)
> 当你第一次运行 App 组件的测试时，**如何**碰到了错误，可能是因为...

> 你已经学习**道**了如何组织和测试你的代码了。让我们**会**在最后一章回顾下吧

**Comment by JimmyLv** [comment]
多谢，已修改。

**Comment by azzgo** [comment]
厉害了

**Comment by Heroor** [comment]
吼吼吼 我又来啦~

##### 1. 代码组织和测试 [chapter4-cn.md](https://github.com/the-road-to-learn-react/the-road-to-learn-react-chinese/blob/master/manuscript/chapter4-cn.md)

-  . . . 另外一个步骤可能要将 App 组件中的变量抽出。这些变量用来组合出 Hacker News 的 API URL。

    ```src/
    index.js
    index.css
    constants/
    index.js
    components/
      App/
        index.js
        test.js
        index..css   // 这里的后缀
      Button/
        index.js
        test.js
        index..css   // 这里的后缀
      ...
    ```


##### 2. 高级React组件 [chapter5-cn.md](https://github.com/the-road-to-learn-react/the-road-to-learn-react-chinese/blob/master/manuscript/chapter5-cn.md)

-  
    ~~~~~~~~
    const Loading = () =>
      <div>Loading ...</div>
    ~~~~~~~~
    
    现在我们需要存储加载状态 (isLoading)。根据加载状态 (isLoading)，决定是否显示 Loading 组件。
    
    ~~~~~~~~
    const Loading = () =>        // 重复了
      <div>Loading ...</div>    // 重复了
    ~~~~~~~~
    
    现在你将需要一个属性来存储加载状态。根据加载状态可以决定稍后是否显示所加载的组件。（重复了）


- > 现在，我们**以**在 JSX 中使用 HOC。应用程序中的用例可能是显示“More”按钮或 Loading
组件 . . .

**Comment by azzgo** [comment]
厉害了 发现 英文原版 也是 `index..css` ，@JimmyLv @Heroor  要不要也和原作者反馈下，（￣︶￣）↗

![image](https://user-images.githubusercontent.com/5636512/36793785-44af50b8-1cd9-11e8-8fc5-29ae0fb56507.png)

chapter5-cn.md 的我已经提提交修复 PR, @JimmyLv  你看下

**Comment by JimmyLv** [comment]
嗯嗯，你们都太棒了，我已经 Merged 了。
