### ISSUE TITLE
P23 链接 45 错误

### ISSUE THREAD

**Issue by CharlesGeng** [the-road-to-learn-react/the-road-to-learn-react-chinese#47]
在2020-12-13版本中，第23页的链接45开头缺少一个字母h：
（误）ttps://....
（正）https://...
因此在点击链接时，网页不能正常打开。

**Comment by kenpusney** [comment]
@CharlesGeng 
多谢提醒，这里是旧版翻译。新版翻译仓库为：[the-road-to-learn-react/the-road-to-react-chinese](https://github.com/the-road-to-learn-react/the-road-to-react-chinese)，您可以移步到那边提供反馈。

**Comment by LiJiahaoCoder** [comment]
> 在2020-12-13版本中，第23页的链接45开头缺少一个字母h：
> （误）ttps://....
> （正）https://...
> 因此在点击链接时，网页不能正常打开。

您好，十分感谢指出问题，《React 学习之道》已发布最新版修复。以后如有其它问题，请在最新版的 Repo 中提出反馈：[the-road-to-react-chinese](https://github.com/the-road-to-learn-react/the-road-to-react-chinese)

**Comment by CharlesGeng** [comment]
谢谢你们的支持，如果有新问题我会在新仓库中提交的。再次感谢！
