### ISSUE TITLE
Chapter 5: Advanced React Components

### ISSUE THREAD

**Issue by JimmyLv** [the-road-to-learn-react/the-road-to-learn-react-chinese#5]
翻译时间：10 天（预估时间：2017 年 12 月 3 日 - 2017 年 12 月 13 日）
翻译作者：@liujiefengfeng（Jiefeng.Liu）

校对时间：x 天（预估时间：x 年 x 月 x 日 - x 年 x 月 x 日）
校对作者：

**Comment by liujiefengfeng** [comment]
翻译时间：10 天（预估时间：2017 年 12 月 3 日 - 2017 年 12 月 13 日）
翻译作者：Rui.Li / Jiiefeng.Liu

校对时间：x 天（预估时间：x 年 x 月 x 日 - x 年 x 月 x 日）
校对作者：

**Comment by JimmyLv** [comment]
经过协商，这个章节就姐夫一个人翻译啦，@liujiefengfeng 快去接受权限 invitation 吧~ 😆

**Comment by liujiefengfeng** [comment]
有些翻译不确定的部分，添加注释 (NOTE: 原文) 。

**Comment by JimmyLv** [comment]
直接在 PR 里面找 reviewers 然后 assign 吧~
