### ISSUE TITLE
Chapter 6: State Management in React and beyond

### ISSUE THREAD

**Issue by JimmyLv** [the-road-to-learn-react/the-road-to-learn-react-chinese#6]
翻译时间：7 天（预估时间：2017 年 12 月 1 日 - 2017 年 12 月 8 日）
翻译作者：@futantan （傅坦坦）

校对时间：x 天（预估时间：x 年 x 月 x 日 - x 年 x 月 x 日）
校对作者：

**Comment by futantan** [comment]
翻译时间：7 天（预估时间：2017 年 12 月 1 日 - 2017 年 12 月 8 日）
翻译作者： 傅坦坦
