### ISSUE TITLE
Addition: Final Steps to Production

### ISSUE THREAD

**Issue by JimmyLv** [the-road-to-learn-react/the-road-to-learn-react-chinese#7]
翻译时间： 9 天（预估时间：2017 年 12 月 02 日 - 2017 年 12 月 10 日）
翻译作者：@linksgo2011 (Ning Lin)

校对时间：x 天（预估时间：x 年 x 月 x 日 - x 年 x 月 x 日）
校对作者：

**Comment by linksgo2011** [comment]
先把这个捡了吧

**Comment by JimmyLv** [comment]
哈哈，棒！👍  预估个时间呢？顺便接受下权限 invitation 哈。。

**Comment by linksgo2011** [comment]
一周吧，把下周周末算上哈，帮我编辑下上面的时间信息 @JimmyLv
