### ISSUE TITLE
Foreword & FAQ

### ISSUE THREAD

**Issue by JimmyLv** [the-road-to-learn-react/the-road-to-learn-react-chinese#8]
翻译时间：x 天（预估时间：x 年 x 月 x 日 - x 年 x 月 x 日）
翻译作者：@LeiZeng (Eric Zeng)

校对时间： 3 天（预估时间：x 年 x 月 x 日 - x 年 x 月 x 日）
校对作者：@JimmyLv

PR 记录：#14

**Comment by LeiZeng** [comment]
前言我领了吧，还没权限，改不了

**Comment by JimmyLv** [comment]
快去接受一下权限噻？https://github.com/the-road-to-learn-react/the-road-to-learn-react-chinese/invitations
